#language: fortran

sudo: required

before_install:
  - ./utilities/scripts/build.sh
#          - sudo apt-get install gfortran
#          - sudo apt-get install gcc
#addons:
#  apt:
#      packages: 
#        - libopenmpi-dev

cache:
 directories:
  - openmpi-2.0.1

script: ./build.sh
#script: make clean && make RFLU=1
