#language: fortran

sudo: true

#dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install libmetis
    #  - ./utilities/scripts/build.sh
    #  - ./build.sh
#          - sudo apt-get install gcc
addons:
 apt:
  packages: 
   - libopenmpi-dev

cache:
 directories:
  - openmpi
  - openmpi-2.0.1

#script: ./build.sh
script: make clean && make RFLU=1 NO_TECPLOT=1
