#language: fortran

sudo: true

#dist: trusty

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install metis
    #  - ./utilities/scripts/build.sh
    #  - ./build.sh
#          - sudo apt-get install gcc
addons:
 apt:
  packages: 
   - libopenmpi-dev

cache:
 directories:
  - openmpi
  - openmpi-2.0.1

#script: ./build.sh
#script: 
# - make clean && make $TARGET
#   # - make clean && make RFLU=1 NO_TECPLOT=1
#   # - make clean && make RFLU=1 FOLDER=1 SPEC=1 NO_TECPLOT=1
#   # - make clean && make RFLU=1 FOLDER=1 SPEC=1 INRT=1 PLAG=1 NO_TECPLOT=1

jobs:
 include:
  - stage: 'Build Test'
    name: 'RFLU, NO_TECPLOT'
    script: make clean && make RFLU=1 NO_TECPLOT=1
  - stage: 'Build Test'
    name: 'RFLU, FOLDER, NO_TECPLOT'
    script: make clean && make RFLU=1 FOLDER=1 NO_TECPLOT=1
  - stage: 'Build Test'
    name: 'RFLU, SPEC, FOLDER, NO_TECPLOT'
    script: make clean && make RFLU=1 FOLDER=1 SPEC=1 NO_TECPLOT=1
  - stage: 'Build Test'
    name: 'RFLU, PLAG, SPEC, FOLDER, NO_TECPLOT'
    script: make clean && make RFLU=1 FOLDER=1 SPEC=1 PLAG=1 NO_TECPLOT=1

notifications:  
  email:  
   recipients:  
    - rahul.koneru@ufl.edu
   on_success: always  
   on_failure: always
