################################################################################
#
# $Id: Makefile.dep,v 1.1.1.1 2015/01/23 22:57:50 tbanerjee Exp $
#
# Purpose: Automatic generation of dependencies for RocfluidMP
#
# Copyright: (c) 2003 by the University of Illinois
#
################################################################################

%.d : %.F90
	@echo "Generating dependency file $*.d from $<"
	@(echo "$*.o: \\"; $(CPP) $(FPPFLAGS) $< | grep "^ *USE " | \
	sed -e "s/[ \t]*USE  *\([0-9a-zA-Z_]*\).*/ \1.o \\\/" \
	| sort -u; echo) > $@

ifneq ($(MAKECMDGOALS),clean)

DEPS		= $(SRCF90:.F90=.d)
ifeq "$(filter-out %.o,$(MAKECMDGOALS))" ""
ifneq "$(MAKECMDGOALS)" ""
# Use only those relevant ones
DEPS= $(filter $(SRCF90:.F90=.d),$(MAKECMDGOALS:.o=.d) placeholder)
endif
endif

ifneq "$(DEPS)" ""
-include 	$(DEPS) 
endif  # ifneq "$(DEPS)" ""
endif  # ifneq ($(MAKECMDGOALS),clean)

################################################################################
#
# RCS Revision history:
#
#   $Log: Makefile.dep,v $
#   Revision 1.1.1.1  2015/01/23 22:57:50  tbanerjee
#   merged rocflu micro and macro
#
#   Revision 1.1.1.1  2014/07/15 14:31:36  brollin
#   New Stable version
#
#   Revision 1.1  2007/04/09 18:42:48  haselbac
#   Initial revision after split from RocfloMP
#
#   Revision 1.1  2007/04/09 17:54:52  haselbac
#   Initial revision after split from RocfloMP
#
#   Revision 1.1  2003/03/20 22:42:13  haselbac
#   Initial revision
#
################################################################################
